services:
  fastapi:
    build: .
    container_name: house-price-api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: house-price-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - fastapi
